### ISSUE TITLE
ROAD MAP

### ISSUE THREAD

**Issue by edhall111** [DavidWigley/Letterman#3]
We need to actually sit down and come up with a plan, like a hard copy that we can visualize. We each need to see what our next step is both individually and as a whole in order to get this project done.

I personally am going to be working on this mainly at night, and whenever I have a good chunk of time I will try to get to BSU to work on it.

**Comment by Trevbon** [comment]
Hmmm which day?

**Comment by DavidWigley** [comment]
Any is good for me but its gotta be before like 4 or so. This works till Monday (6/13) for me. Next week is sorta weird for me and wont be free till later that week.

**Comment by DavidWigley** [comment]
road map is listed on another issue.

**Comment by Trevbon** [comment]
Perfect

**Comment by Trevbon** [comment]
PNGs
